### ISSUE TITLE
If a callback throws an exception, Consumer.wait() hangs.

### ISSUE THREAD

**Issue by danielrichman** [benoitc/couchdbkit#147]
``` python
>>> import couchdbkit
>>> db = couchdbkit.Server("http://localhost:5984")["temp"]
>>> c = couchdbkit.Consumer(db)
>>> def cb(*args):
...     print "In callback"
...     raise ValueError
... 
>>> c.wait(cb)
In callback
```

Nothing is printed after this point, and the process hangs. It continues to read from _changes, though it does nothing.

Control-C reveals where it's stuck:

``` python
^CTraceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/daniel/temp/src/couchdbkit/couchdbkit/consumer/__init__.py", line 103, in wait
    return self._consumer.wait(cb, **params)
  File "/home/daniel/temp/src/couchdbkit/couchdbkit/consumer/sync.py", line 56, in wait
    break
  File "/home/daniel/temp/lib/python2.6/site-packages/restkit/wrappers.py", line 161, in __exit__
    self.close()
  File "/home/daniel/temp/lib/python2.6/site-packages/restkit/wrappers.py", line 169, in close
    self.body.read()
  File "/usr/lib/python2.6/io.py", line 940, in read
    return self._read_unlocked(n)
  File "/usr/lib/python2.6/io.py", line 955, in _read_unlocked
    chunk = self.raw.read()
  File "/usr/lib/python2.6/io.py", line 589, in read
    return self.readall()
  File "/usr/lib/python2.6/io.py", line 599, in readall
    data = self.read(DEFAULT_BUFFER_SIZE)
  File "/usr/lib/python2.6/io.py", line 591, in read
    n = self.readinto(b)
  File "/home/daniel/temp/lib/python2.6/site-packages/http_parser/reader.py", line 60, in readinto
    recved = self.http_stream.stream.readinto(buf)
  File "/home/daniel/temp/lib/python2.6/site-packages/http_parser/reader.py", line 150, in readinto
    return _readinto(self._sock, b)
  File "/home/daniel/temp/lib/python2.6/site-packages/http_parser/reader.py", line 25, in _readinto
    buf = sock.recv(l)
KeyboardInterrupt
```

As far as I can tell, __ exit __ is called because of the 'with restkit wrapper:' block in sync.py. It then attempts to read the remainder of the stream, which it can't do because continuous changes never ends.

The above console output was produced after installing 'git://github.com/benoitc/couchdbkit.git#egg=couchdbkit' into a clean virtualenv, though I get the same problem with couchdbkit 0.6.3 on python2.7 on another box.

Thanks,
Daniel

**Comment by bobbymiller** [comment]
+1
