### ISSUE TITLE
pip install in windows (python3) returns errors

### ISSUE THREAD

**Issue by paweueck** [benoitc/couchdbkit#193]
C:\WINDOWS\system32>pip install couchdbkit
Collecting couchdbkit
  Using cached couchdbkit-0.6.5.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "C:\Users\paweueck\AppData\Local\Temp\pip-build-32bitqqx\couchdbkit\setup.py", line 25, in <module>
        long_description = file(
    NameError: name 'file' is not defined

    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in C:\Users\paweueck\AppData\Local\Temp\pip-build-32bitqqx\couchdbkit\

I also tried installing with conda but it also does not work...

C:\WINDOWS\system32>conda install couchdbkit
Fetching package metadata .............

PackageNotFoundError: Package missing in current win-64 channels:
  - couchdbkit

**Comment by TerabyteTiger** [comment]
I'm also experiencing this issue :(

**Comment by domdinicola** [comment]
python 2.x is leaving/left us, support to python should be a must if this project is still alive
